### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by bitsofinfo** [jwilsoncredera/gradle-profiles#1]
How are you working on this project in an IDE, for example Eclipse. I'd like to import it into eclipse but when I do, (after doing gradle eclipse) its not really setup, for src folders etc, nothing compiles or references eachother properly. Is it one project for the root, or separate eclipse projects for each subproject?

Forget it, I need to reread the article

**Comment by jdwilson11** [comment]
Running "gradle eclipse" and then importing it into your IDE as an Eclipse project should do the trick.

As an FYI for anyone else looking at this, here's the link to the referenced article:
https://www.credera.com/blog/technology-insights/java/gradle-profiles-for-multi-project-spring-boot-applications/
